/**
 * Maps every team ID to its home venue ID.
 * Used as a fallback when a game's venueId is null (e.g. manually-logged games
 * where the city-based auto-fill didn't find a match), and to show venue names
 * on wishlist entries. Multi-sport venues appear under each sport that uses them.
 */
export const TEAM_HOME_VENUE: Record<string, string> = {
  // ── NFL (32 teams) ──────────────────────────────────────────
  "nfl-ari": "v-state-farm",
  "nfl-atl": "v-mb-stadium",      // shared with MLS Atlanta United
  "nfl-bal": "v-mt-bank",
  "nfl-buf": "v-highmark",
  "nfl-car": "v-bank-of-america",
  "nfl-chi": "v-soldier",
  "nfl-cin": "v-paycor",
  "nfl-cle": "v-huntington-bank",
  "nfl-dal": "v-att",
  "nfl-den": "v-empower",
  "nfl-det": "v-ford",
  "nfl-gb":  "v-lambeau",
  "nfl-hou": "v-nrg",
  "nfl-ind": "v-lucas-oil",
  "nfl-jax": "v-everbank",
  "nfl-kc":  "v-arrowhead",
  "nfl-lac": "v-sofi",
  "nfl-lar": "v-sofi",
  "nfl-lv":  "v-allegiant",
  "nfl-mia": "v-hard-rock",
  "nfl-min": "v-usbank",
  "nfl-ne":  "v-gillette",
  "nfl-no":  "v-caesars-dome",
  "nfl-nyg": "v-metlife",
  "nfl-nyj": "v-metlife",
  "nfl-phi": "v-linc",
  "nfl-pit": "v-acrisure",
  "nfl-sf":  "v-levis",
  "nfl-sea": "v-lumen",           // shared with MLS Seattle Sounders
  "nfl-tb":  "v-raymond-james",
  "nfl-ten": "v-nissan",
  "nfl-was": "v-northwest",
  // ── MLB (30 teams) ──────────────────────────────────────────
  "mlb-ari": "v-chase-field",
  "mlb-atl": "v-truist",
  "mlb-bal": "v-camden",
  "mlb-bos": "v-fenway",
  "mlb-chc": "v-wrigley",
  "mlb-cws": "v-guaranteed-rate",
  "mlb-cin": "v-gabp",
  "mlb-cle": "v-progressive",
  "mlb-col": "v-coors",
  "mlb-det": "v-comerica",
  "mlb-hou": "v-minute-maid",
  "mlb-kc":  "v-kauffman",
  "mlb-laa": "v-angel",
  "mlb-lad": "v-dodger",
  "mlb-mia": "v-loandepot",
  "mlb-mil": "v-american-family",
  "mlb-min": "v-target-field",
  "mlb-nym": "v-citi",
  "mlb-nyy": "v-yankee",
  "mlb-oak": "v-sutter",          // Sacramento Athletics (temp home)
  "mlb-phi": "v-citizens-bank",
  "mlb-pit": "v-pnc",
  "mlb-sd":  "v-petco",
  "mlb-sea": "v-tmobile-park",
  "mlb-sf":  "v-oracle",
  "mlb-stl": "v-busch",
  "mlb-tb":  "v-tropicana",
  "mlb-tex": "v-globe-life",
  "mlb-tor": "v-rogers-centre",
  "mlb-was": "v-nationals-park",
  // ── NBA (30 teams) ──────────────────────────────────────────
  "nba-atl": "v-state-farm-arena",
  "nba-bos": "v-td-garden",
  "nba-bkn": "v-barclays",
  "nba-cha": "v-spectrum",
  "nba-chi": "v-united-center",
  "nba-cle": "v-rocket-mortgage",
  "nba-dal": "v-aac",
  "nba-den": "v-ball-arena",
  "nba-det": "v-little-caesars",
  "nba-gsw": "v-chase",
  "nba-hou": "v-toyota-center",
  "nba-ind": "v-gainbridge",
  "nba-lac": "v-intuit",
  "nba-lal": "v-crypto",
  "nba-mem": "v-fedexforum",
  "nba-mia": "v-kaseya",
  "nba-mil": "v-fiserv",
  "nba-min": "v-target-center",
  "nba-nop": "v-smoothie-king",
  "nba-nyk": "v-msg",
  "nba-okc": "v-paycom",
  "nba-orl": "v-kia-center",
  "nba-phi": "v-wells-fargo",     // shared with NHL Flyers
  "nba-phx": "v-footprint",
  "nba-por": "v-moda",
  "nba-sac": "v-golden1",
  "nba-sas": "v-att-center",
  "nba-tor": "v-scotiabank",      // shared with NHL Maple Leafs
  "nba-uta": "v-delta",
  "nba-was": "v-capital-one",     // shared with NHL Capitals
  // ── NHL (32 teams) ──────────────────────────────────────────
  "nhl-ana": "v-honda",
  "nhl-bos": "v-td-garden",       // shared with NBA Celtics
  "nhl-buf": "v-keybank",
  "nhl-cgy": "v-saddledome",
  "nhl-car": "v-pnc-arena",
  "nhl-chi": "v-united-center",   // shared with NBA Bulls
  "nhl-col": "v-ball-arena",      // shared with NBA Nuggets
  "nhl-cbj": "v-nationwide",
  "nhl-dal": "v-aac",             // shared with NBA Mavericks
  "nhl-det": "v-little-caesars",  // shared with NBA Pistons
  "nhl-edm": "v-rogers-place",
  "nhl-fla": "v-amerant",
  "nhl-lak": "v-crypto",          // shared with NBA Lakers/Clippers (old arena)
  "nhl-min": "v-xcel",
  "nhl-mtl": "v-bell-centre",
  "nhl-nsh": "v-bridgestone",
  "nhl-njd": "v-prudential",
  "nhl-nyi": "v-ubs",
  "nhl-nyr": "v-msg",             // shared with NBA Knicks
  "nhl-ott": "v-canadian-tire",
  "nhl-phi": "v-wells-fargo",
  "nhl-pit": "v-ppg-paints",
  "nhl-sjs": "v-sap",
  "nhl-sea": "v-climate-pledge",
  "nhl-stl": "v-enterprise",
  "nhl-tbl": "v-amalie",
  "nhl-tor": "v-scotiabank",
  "nhl-uta": "v-delta",           // shared with NBA Jazz
  "nhl-van": "v-rogers-arena",
  "nhl-vgk": "v-t-mobile",
  "nhl-wpg": "v-canada-life",
  "nhl-wsh": "v-capital-one",
  // ── MLS (29 teams) ──────────────────────────────────────────
  "mls-atl": "v-mb-stadium",
  "mls-atx": "v-q2",
  "mls-clt": "v-bank-of-america", // shared with NFL Panthers
  "mls-chi": "v-soldier",         // shared with NFL Bears
  "mls-cin": "v-tql",
  "mls-col": "v-dicks-sg",
  "mls-clb": "v-lower-com",
  "mls-dc":  "v-audi",
  "mls-dal": "v-toyota-stadium",
  "mls-hou": "v-shell",
  "mls-mia": "v-chase-stadium",
  "mls-la":  "v-dignity",
  "mls-lafc":"v-bmo",
  "mls-min": "v-allianz",
  "mls-mtl": "v-saputo",
  "mls-nsh": "v-geodis",
  "mls-ne":  "v-gillette",        // shared with NFL Patriots
  "mls-nyc": "v-yankee",          // NYCFC (temp home at Yankee Stadium)
  "mls-nyrb":"v-red-bull-arena",
  "mls-orl": "v-exploria",
  "mls-phi": "v-subaru",
  "mls-por": "v-providence",
  "mls-rsl": "v-america-first",
  "mls-sea": "v-lumen",
  "mls-sj":  "v-paypal",
  "mls-skc": "v-children-mercy",
  "mls-stl": "v-citypark",
  "mls-tor": "v-bmo-field",
  "mls-van": "v-bc-place",
};
